name: Unit Test / Lint / Bundle Watch

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: |
          npm run lint
          npm run type

      - name: Test
        run: |
          npm run test

      - name: Bundle watch
        run: |
          npm run bundlewatch
